version: "3.3"

services:
  db:
    image: postgres:15
    container_name: eco_kamchatka_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EcoKamchatka
    volumes:
      - /home/user1/DOCKER/eco_kamchatka_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: eco_kamchatka_api
    restart: always
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/user1/kamchatka_api/photos:/app/photos
      - /home/user1/kamchatka_api/documents:/app/documents
